// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhqE8aaIfD08ShOsRdCBlbgTfGePVgU5Y',
    appId: '1:221220347616:web:66a76493e6d97bfcce3a85',
    messagingSenderId: '221220347616',
    projectId: 'chatapp-9e27f',
    authDomain: 'chatapp-9e27f.firebaseapp.com',
    storageBucket: 'chatapp-9e27f.appspot.com',
    measurementId: 'G-TT0VM9ZYFE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDop3arLI6HsUxRnoVwIg6lM-ZXsLwMlMM',
    appId: '1:221220347616:android:fa62c9726b25833ace3a85',
    messagingSenderId: '221220347616',
    projectId: 'chatapp-9e27f',
    storageBucket: 'chatapp-9e27f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0HxaaojyJ8knhzoUgFvzeVdMG5Olj7y4',
    appId: '1:221220347616:ios:cd0e0e7bf3480eebce3a85',
    messagingSenderId: '221220347616',
    projectId: 'chatapp-9e27f',
    storageBucket: 'chatapp-9e27f.appspot.com',
    iosBundleId: 'com.example.flutterProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0HxaaojyJ8knhzoUgFvzeVdMG5Olj7y4',
    appId: '1:221220347616:ios:cd0e0e7bf3480eebce3a85',
    messagingSenderId: '221220347616',
    projectId: 'chatapp-9e27f',
    storageBucket: 'chatapp-9e27f.appspot.com',
    iosBundleId: 'com.example.flutterProject',
  );
}
